org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
tdmc_version=1.0.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=tl_survival_elements
mod_name=生存要素
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.szypxj.tlsurvivalelements
mod_authors=szypxj
mod_description=TDMC survival attributes addon with food, hydration, stamina and unified HUD.
